### CUSTOMERS 

### get all the customers 

GET http://localhost:8000/customers


### Add a new customer to the database

POST http://localhost:8000/customers

Content-Type: application/json

{
  "name" : "user2",
  "email" : "User12@gmail.com",
  "phone" : 5515455555
}


### get specific customer orders

GET  http://localhost:8000/customers/orders

Content-Type: application/json

{
  "phone" : "5515455555"
}


### get customer with max orders

GET http://localhost:8000/customers/maxOrder



### PRODUCTS

### get all the products

GET http://localhost:8000/products


### Add a new product to the database

POST http://localhost:8000/products

Content-Type: application/json

{
  "productName" : "Potato", 
  "productCategory" : "Vegitable", 
  "productInfo" : "", 
  "price" : 50, 
  "quantityAvailable" : "500"
}


### update product price

PUT  http://localhost:8000/products/price

Content-Type: application/json

{
  "product" : "Mango",
  "price" : 200
}


### ORDERS

### create a new order

POST  http://localhost:8000/order

Content-Type: application/json

{
  "phone" : "5515455555",
  "products":[{"name" : "Mango", "quantity" : 1}, {"name": "Apple", "quantity" : 1}], 
  "paymentType": "abc"
}
